-- ARTICLES TABLE
CREATE TABLE IF NOT EXISTS public.articles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    title           TEXT NOT NULL,
    source_url      TEXT NOT NULL UNIQUE,
    source_name     TEXT NOT NULL,
    summary         TEXT NOT NULL,
    raw_content     TEXT,
    category        TEXT NOT NULL,
    score           DECIMAL(3,1),
    image_url       TEXT,
    published_date  TIMESTAMPTZ NOT NULL,
    is_published    BOOLEAN DEFAULT false
);

CREATE INDEX idx_articles_category ON public.articles(category);
CREATE INDEX idx_articles_score ON public.articles(score);
CREATE INDEX idx_articles_published_date ON public.articles(published_date);
CREATE INDEX idx_articles_is_published ON public.articles(is_published);

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Published articles are publicly readable"
ON public.articles FOR SELECT
USING (is_published = true);

-- SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Settings are publicly readable"
ON public.settings FOR SELECT
USING (true);

-- ANALYTICS TABLE
CREATE TABLE IF NOT EXISTS public.analytics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    page_views      INTEGER DEFAULT 0,
    unique_visitors INTEGER DEFAULT 0,
    ad_revenue      DECIMAL(10,2) DEFAULT 0
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Analytics are publicly readable"
ON public.analytics FOR SELECT
USING (true);

-- UPDATE TIMESTAMP TRIGGER
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON public.articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_settings_updated_at
BEFORE UPDATE ON public.settings
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- Supabase Migration: Add article images support (updated - skips duplicates)

-- Create article_images table to store multiple images per article
CREATE TABLE IF NOT EXISTS public.article_images (
  id BIGSERIAL PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  alt_text TEXT,
  position INTEGER NOT NULL DEFAULT 0,
  width INTEGER DEFAULT 1200,
  height INTEGER,
  size_kb INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for article_images
CREATE INDEX IF NOT EXISTS idx_article_images_article_id ON public.article_images(article_id);
CREATE INDEX IF NOT EXISTS idx_article_images_position ON public.article_images(position);

-- Enable RLS on article_images
ALTER TABLE public.article_images ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for article_images
-- Drop existing policies if they exist (optional - comment out if not needed)
-- DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
-- DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;

CREATE POLICY "Allow public read access to article_images"
  ON public.article_images
  FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to manage images"
  ON public.article_images
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Add new columns to articles table (IF NOT EXISTS)
ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS is_draft BOOLEAN DEFAULT TRUE;

ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS admin_notes TEXT;

ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS scheduled_publish_date TIMESTAMP WITH TIME ZONE;

-- Create index for is_draft (IF NOT EXISTS)
CREATE INDEX IF NOT EXISTS idx_articles_is_draft ON public.articles(is_draft);

-- Add comment
COMMENT ON TABLE article_images IS 'Stores multiple images for each article - supports 4-5 images per article at 1200px minimum width';

-- Verify migration
SELECT 
  'article_images table' as check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'article_images') as exists
UNION ALL
SELECT 
  'is_draft column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'is_draft')
UNION ALL
SELECT 
  'admin_notes column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'admin_notes')
UNION ALL
SELECT 
  'scheduled_publish_date column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'scheduled_publish_date');


-- COMPLETE DATABASE MIGRATION FOR ORIGINAL CONTENT SYSTEM
-- Run this in Supabase SQL Editor
-- FIXED: Removed IF NOT EXISTS from CREATE POLICY (not supported)

-- ============================================================================
-- ARTICLES TABLE - Updated for original content + image support
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.articles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    title           TEXT NOT NULL,
    source_url      TEXT,
    source_name     TEXT,
    summary         TEXT NOT NULL,
    raw_content     TEXT,
    category        TEXT NOT NULL,
    score           DECIMAL(3,1),
    image_url       TEXT,
    published_date  TIMESTAMPTZ NOT NULL,
    is_published    BOOLEAN DEFAULT false,
    is_draft        BOOLEAN DEFAULT true,
    admin_notes     TEXT,
    scheduled_publish_date TIMESTAMPTZ
);

-- Create indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_articles_category ON public.articles(category);
CREATE INDEX IF NOT EXISTS idx_articles_score ON public.articles(score);
CREATE INDEX IF NOT EXISTS idx_articles_published_date ON public.articles(published_date);
CREATE INDEX IF NOT EXISTS idx_articles_is_published ON public.articles(is_published);
CREATE INDEX IF NOT EXISTS idx_articles_is_draft ON public.articles(is_draft);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON public.articles(created_at);

-- Enable Row Level Security
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Published articles are publicly readable" ON public.articles;
DROP POLICY IF EXISTS "Admins can read all articles" ON public.articles;

-- RLS Policy: Anyone can read published articles
CREATE POLICY "Published articles are publicly readable"
ON public.articles FOR SELECT
USING (is_published = true);

-- RLS Policy: Authenticated users (admin) can read all articles
CREATE POLICY "Admins can read all articles"
ON public.articles FOR SELECT
USING (auth.role() = 'authenticated');

-- Update trigger for updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Drop trigger if exists, then create
DROP TRIGGER IF EXISTS update_articles_updated_at ON public.articles;
CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON public.articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- ARTICLE_IMAGES TABLE - For storing multiple images per article
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.article_images (
  id              BIGSERIAL PRIMARY KEY,
  article_id      BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  image_url       TEXT NOT NULL,
  alt_text        TEXT,
  position        INTEGER NOT NULL DEFAULT 0,
  width           INTEGER DEFAULT 1200,
  height          INTEGER,
  size_kb         INTEGER,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_article_images_article_id ON public.article_images(article_id);
CREATE INDEX IF NOT EXISTS idx_article_images_position ON public.article_images(position);

-- Enable RLS
ALTER TABLE public.article_images ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;

-- RLS Policies
CREATE POLICY "Allow public read access to article_images"
  ON public.article_images
  FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to manage images"
  ON public.article_images
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Update trigger for article_images
DROP TRIGGER IF EXISTS update_article_images_updated_at ON public.article_images;
CREATE TRIGGER update_article_images_updated_at
BEFORE UPDATE ON public.article_images
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- SETTINGS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Settings are publicly readable" ON public.settings;

CREATE POLICY "Settings are publicly readable"
ON public.settings FOR SELECT
USING (true);

-- ============================================================================
-- ANALYTICS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.analytics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    page_views      INTEGER DEFAULT 0,
    unique_visitors INTEGER DEFAULT 0,
    ad_revenue      DECIMAL(10,2) DEFAULT 0
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Analytics are publicly readable" ON public.analytics;

CREATE POLICY "Analytics are publicly readable"
ON public.analytics FOR SELECT
USING (true);

-- ============================================================================
-- VERIFICATION QUERIES - Run these to verify everything is set up correctly
-- ============================================================================

SELECT 
  'articles table exists' as check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'articles') as result
UNION ALL
SELECT 
  'article_images table exists',
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'article_images')
UNION ALL
SELECT 
  'is_draft column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'is_draft')
UNION ALL
SELECT 
  'admin_notes column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'admin_notes')
UNION ALL
SELECT 
  'scheduled_publish_date column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'scheduled_publish_date');


-- Only these 3 lines are missing from your existing migration

ALTER TABLE public.articles
  DROP CONSTRAINT IF EXISTS articles_source_url_key;

ALTER TABLE public.articles
  ALTER COLUMN source_url DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_articles_source_url_unique
  ON public.articles(source_url)
  WHERE source_url IS NOT NULL;

-- ============================================================================
-- FIX: Allow anon key to read/write/delete draft articles in admin panel
-- The problem: RLS blocks anon users from seeing is_draft=true articles
-- ============================================================================

-- DROP all existing article policies first
DROP POLICY IF EXISTS "Published articles are publicly readable" ON public.articles;
DROP POLICY IF EXISTS "Admins can read all articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to insert articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to update articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to delete articles" ON public.articles;

-- DROP all existing article_images policies
DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;
DROP POLICY IF EXISTS "Allow admin to insert images" ON public.article_images;
DROP POLICY IF EXISTS "Allow admin to delete images" ON public.article_images;

-- ============================================================================
-- ARTICLES: New policies
-- ============================================================================

-- 1. Anyone can read published articles (public website)
CREATE POLICY "Public can read published articles"
ON public.articles FOR SELECT
USING (is_published = true);

-- 2. Anon key can read ALL articles (needed for admin panel drafts)
CREATE POLICY "Anon can read all articles"
ON public.articles FOR SELECT
USING (true);

-- 3. Anon key can insert articles (needed for generate button)
CREATE POLICY "Anon can insert articles"
ON public.articles FOR INSERT
WITH CHECK (true);

-- 4. Anon key can update articles (needed for publish, notes)
CREATE POLICY "Anon can update articles"
ON public.articles FOR UPDATE
USING (true)
WITH CHECK (true);

-- 5. Anon key can delete articles (needed for bulk delete)
CREATE POLICY "Anon can delete articles"
ON public.articles FOR DELETE
USING (true);

-- ============================================================================
-- ARTICLE_IMAGES: New policies
-- ============================================================================

-- 1. Anyone can read images
CREATE POLICY "Public can read article images"
ON public.article_images FOR SELECT
USING (true);

-- 2. Anon can insert images
CREATE POLICY "Anon can insert article images"
ON public.article_images FOR INSERT
WITH CHECK (true);

-- 3. Anon can delete images
CREATE POLICY "Anon can delete article images"
ON public.article_images FOR DELETE
USING (true);

-- 4. Anon can update images
CREATE POLICY "Anon can update article images"
ON public.article_images FOR UPDATE
USING (true)
WITH CHECK (true);

-- ============================================================================
-- VERIFY: Check all policies are in place
-- ============================================================================
SELECT 
  schemaname,
  tablename,
  policyname,
  cmd
FROM pg_policies
WHERE tablename IN ('articles', 'article_images')
ORDER BY tablename, cmd;