-- ARTICLES TABLE
CREATE TABLE IF NOT EXISTS public.articles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    title           TEXT NOT NULL,
    source_url      TEXT NOT NULL UNIQUE,
    source_name     TEXT NOT NULL,
    summary         TEXT NOT NULL,
    raw_content     TEXT,
    category        TEXT NOT NULL,
    score           DECIMAL(3,1),
    image_url       TEXT,
    published_date  TIMESTAMPTZ NOT NULL,
    is_published    BOOLEAN DEFAULT false
);

CREATE INDEX idx_articles_category ON public.articles(category);
CREATE INDEX idx_articles_score ON public.articles(score);
CREATE INDEX idx_articles_published_date ON public.articles(published_date);
CREATE INDEX idx_articles_is_published ON public.articles(is_published);

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Published articles are publicly readable"
ON public.articles FOR SELECT
USING (is_published = true);

-- SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Settings are publicly readable"
ON public.settings FOR SELECT
USING (true);

-- ANALYTICS TABLE
CREATE TABLE IF NOT EXISTS public.analytics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    page_views      INTEGER DEFAULT 0,
    unique_visitors INTEGER DEFAULT 0,
    ad_revenue      DECIMAL(10,2) DEFAULT 0
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Analytics are publicly readable"
ON public.analytics FOR SELECT
USING (true);

-- UPDATE TIMESTAMP TRIGGER
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON public.articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_settings_updated_at
BEFORE UPDATE ON public.settings
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();