-- ARTICLES TABLE
CREATE TABLE IF NOT EXISTS public.articles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    title           TEXT NOT NULL,
    source_url      TEXT NOT NULL UNIQUE,
    source_name     TEXT NOT NULL,
    summary         TEXT NOT NULL,
    raw_content     TEXT,
    category        TEXT NOT NULL,
    score           DECIMAL(3,1),
    image_url       TEXT,
    published_date  TIMESTAMPTZ NOT NULL,
    is_published    BOOLEAN DEFAULT false
);

CREATE INDEX idx_articles_category ON public.articles(category);
CREATE INDEX idx_articles_score ON public.articles(score);
CREATE INDEX idx_articles_published_date ON public.articles(published_date);
CREATE INDEX idx_articles_is_published ON public.articles(is_published);

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Published articles are publicly readable"
ON public.articles FOR SELECT
USING (is_published = true);

-- SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Settings are publicly readable"
ON public.settings FOR SELECT
USING (true);

-- ANALYTICS TABLE
CREATE TABLE IF NOT EXISTS public.analytics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    page_views      INTEGER DEFAULT 0,
    unique_visitors INTEGER DEFAULT 0,
    ad_revenue      DECIMAL(10,2) DEFAULT 0
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Analytics are publicly readable"
ON public.analytics FOR SELECT
USING (true);

-- UPDATE TIMESTAMP TRIGGER
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON public.articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_settings_updated_at
BEFORE UPDATE ON public.settings
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- Supabase Migration: Add article images support (updated - skips duplicates)

-- Create article_images table to store multiple images per article
CREATE TABLE IF NOT EXISTS public.article_images (
  id BIGSERIAL PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  alt_text TEXT,
  position INTEGER NOT NULL DEFAULT 0,
  width INTEGER DEFAULT 1200,
  height INTEGER,
  size_kb INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for article_images
CREATE INDEX IF NOT EXISTS idx_article_images_article_id ON public.article_images(article_id);
CREATE INDEX IF NOT EXISTS idx_article_images_position ON public.article_images(position);

-- Enable RLS on article_images
ALTER TABLE public.article_images ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for article_images
-- Drop existing policies if they exist (optional - comment out if not needed)
-- DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
-- DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;

CREATE POLICY "Allow public read access to article_images"
  ON public.article_images
  FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to manage images"
  ON public.article_images
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Add new columns to articles table (IF NOT EXISTS)
ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS is_draft BOOLEAN DEFAULT TRUE;

ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS admin_notes TEXT;

ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS scheduled_publish_date TIMESTAMP WITH TIME ZONE;

-- Create index for is_draft (IF NOT EXISTS)
CREATE INDEX IF NOT EXISTS idx_articles_is_draft ON public.articles(is_draft);

-- Add comment
COMMENT ON TABLE article_images IS 'Stores multiple images for each article - supports 4-5 images per article at 1200px minimum width';

-- Verify migration
SELECT 
  'article_images table' as check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'article_images') as exists
UNION ALL
SELECT 
  'is_draft column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'is_draft')
UNION ALL
SELECT 
  'admin_notes column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'admin_notes')
UNION ALL
SELECT 
  'scheduled_publish_date column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'scheduled_publish_date');